# Generated by Django 2.2.13 on 2020-07-16 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=50, unique=True)),
                ('pid', models.CharField(blank=True, max_length=24, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField()),
                ('category', models.SmallIntegerField(choices=[(1, 'dashboard'), (2, 'layer'), (3, 'map'), (4, 'document'), (5, 'study')])),
            ],
            options={
                'ordering': ['-last_update'],
            },
        ),
    ]
